[features]
seeds = false
skip-lint = false
[programs.devnet]
vd1 = "35TKZPztLWEgif2x6RAYKTR5Tkqa7euB19sYSqrC3M6c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/buithinh/.config/solana/wallet2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
